<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_gatewayEditAccount SetupChoose your Or_2f36a6</name>
   <tag></tag>
   <elementGuidId>7e53df30-54fb-4648-8db3-f4f80e1df293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gatewayEdit:Account SetupChoose your Organization and Primary LanguageTranslation SettingsOrganizationtest_orgOrganizationPrimary Translating Language​Primary Translating LanguageSave and Continuev0.9.0 build 736dc08{&quot;props&quot;:{&quot;pageProps&quot;:{}},&quot;page&quot;:&quot;/&quot;,&quot;query&quot;:{},&quot;buildId&quot;:&quot;N4Y7bsG8bAWxlf9Y4ted-&quot;,&quot;runtimeConfig&quot;:{},&quot;nextExport&quot;:true,&quot;autoExport&quot;:true,&quot;isFallback&quot;:false}id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button&quot;]am - Amharic - አማርኛar - Arabic - العربيةar-x-dcv - Arabic - Dominant Culture Variant - العربية Dominant Culture Variantas - Assamese - অসমীয়াbi - Bislama - Bislamabn - Bengali, Bangla - বাংলাceb - Cebuano - Cebuanocmn-x-omc -  - Oral Mandarin Chineseen - English - Englishes - Spanish - españoles-419 - Latin American Spanish - Español Latin Americafa - Persian (Farsi) - فارسیfr - French - français, langue françaisegu - Gujarati - ગુજરાતીha - Hausa - (Hausa) هَوُسَhi - Hindi - हिन्दी, हिंदीhi-x-dcv - Hindi - Dominant Culture Variant - हिन्दी, हिंदी - Dominant Culture Variantid - Indonesian - Bahasa Indonesiaid-x-dcv -  - Bahasa Indonesia - Dominant Culture Variantilo - Ilocano - Ilokokm - Khmer - ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរkn - Kannada - ಕನ್ನಡlo - Laotian - ພາສາລາວml - Malayalam - മലയാളംmn - Mongolian - Монгол хэлmr - Marathi (Marāṭhī) - मराठीms - Malay - bahasa Melayu, بهاس ملايو‎my - Burmese - ျမန္မာစာne - Nepali - नेपालीor - Oriya - ଓଡ଼ିଆpa - Panjabi, Punjabi - ਪੰਜਾਬੀ, پنجابی‎pes - Persian, Iranian - فارسیplt - Malagasy, Plateau - Plateau Malagasypmy - Malay, Papuan - Papuan Malayps - Pashto, Pushto - پښتوpt - Portuguese - portuguêspt-br - Brazilian Portuguese - Portuguêsru - Russian - Русскийsw - Swahili - Kiswahilita - Tamil - தமிழ்te - Telugu - తెలుగుth - Thai - ไทยtl - Tagalog - Wikang Tagalogtpi - Tok Pisin - Tok Pisintr - Turkish - Türkçeur - Urdu - اردوur-x-dcv - Urdu - Dominant Culture Variant - اردو - Dominant Culture Variantvi - Vietnamese - Tiếng Việtzh - Chinese - 中文 (Zhōngwén), 汉语, 漢語</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
