<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_gatewayEditAccount SetupChoose your Or_4da2de</name>
   <tag></tag>
   <elementGuidId>38cf3a11-852f-4ddc-a0e3-f25aab160a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'gatewayEdit:Account SetupChoose your Organization and Primary LanguageTranslation SettingsOrganization​OrganizationPrimary Translating Language​Primary Translating LanguageSave and Continuev0.9.0 build 736dc08{&quot;props&quot;:{&quot;pageProps&quot;:{}},&quot;page&quot;:&quot;/&quot;,&quot;query&quot;:{},&quot;buildId&quot;:&quot;N4Y7bsG8bAWxlf9Y4ted-&quot;,&quot;runtimeConfig&quot;:{},&quot;nextExport&quot;:true,&quot;autoExport&quot;:true,&quot;isFallback&quot;:false}id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button&quot;]es-419_TESTtest_orgtest_org2translate_testunfoldingWord' or . = 'gatewayEdit:Account SetupChoose your Organization and Primary LanguageTranslation SettingsOrganization​OrganizationPrimary Translating Language​Primary Translating LanguageSave and Continuev0.9.0 build 736dc08{&quot;props&quot;:{&quot;pageProps&quot;:{}},&quot;page&quot;:&quot;/&quot;,&quot;query&quot;:{},&quot;buildId&quot;:&quot;N4Y7bsG8bAWxlf9Y4ted-&quot;,&quot;runtimeConfig&quot;:{},&quot;nextExport&quot;:true,&quot;autoExport&quot;:true,&quot;isFallback&quot;:false}id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button&quot;]es-419_TESTtest_orgtest_org2translate_testunfoldingWord')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gatewayEdit:Account SetupChoose your Organization and Primary LanguageTranslation SettingsOrganization​OrganizationPrimary Translating Language​Primary Translating LanguageSave and Continuev0.9.0 build 736dc08{&quot;props&quot;:{&quot;pageProps&quot;:{}},&quot;page&quot;:&quot;/&quot;,&quot;query&quot;:{},&quot;buildId&quot;:&quot;N4Y7bsG8bAWxlf9Y4ted-&quot;,&quot;runtimeConfig&quot;:{},&quot;nextExport&quot;:true,&quot;autoExport&quot;:true,&quot;isFallback&quot;:false}id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button&quot;]es-419_TESTtest_orgtest_org2translate_testunfoldingWord</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
