<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Large size</name>
   <tag></tag>
   <elementGuidId>550c3e53-1e98-4a15-89eb-07c431206810</elementGuidId>
   <imagePath>Screenshots/Targets/Page_1624036810434/Element_1624036811738.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_1624036810434/Element_1624036811738.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1624036811738</value>
   </webElementProperties>
</WebElementEntity>
